#Example basic CI!
name: Robonnx CI

on:
  push:
    branches:
    - main

jobs:
   Ubuntu-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Install
          run: python -m pip install .
          
        - name: Unit Testing
          run: python -m pytest -v
          
        - name: Run example inference
          run: python robonnx/roberta_onnx.py
